export const normalizar = (nombre) => {
  if (nombre === "C++") return "cpp";
  if (nombre === "TypeScript") return "typescript";
  if (nombre === "HTML") return "html";
  if (nombre === "CSS") return "css";
  if (nombre === "Python") return "python";
  if (nombre === "JavaScript") return "javascript";
  if (nombre === "Git") return "git";
  if (nombre === "Bootstrap") return "bootstrap";
  if (nombre === "Django") return "django";
  if (nombre === "PHP") return "php";
  if (nombre === "MySQL") return "mysql";
  if (nombre === "PostgreSQL") return "postgresql";
  if (nombre === "SQLite") return "sqlite";
  if (nombre === "Tailwind CSS") return "tailwindcss";
  if (nombre === "React") return "react";
  if (nombre === "ASP.NET Core") return "aspnetcore";
  if (nombre === "Docker") return "docker";
  if (nombre === "Figma") return "figma";
  if (nombre === "Jira") return "jira";
  if (nombre === "Slack") return "slack";
  if (nombre === "Notion") return "notion";
  if (nombre === "Node.js") return "nodejs";
  return nombre.toLowerCase().replace(/\s+/g, "-");
};
